-- FLUSH 
ALTER SYSTEM FLUSH buffer_cache;
ALTER SYSTEM FLUSH shared_pool;

VARIABLE  START_TIME_EKS1_SQL NUMBER;
EXEC :START_TIME_EKS1_SQL := EXTRACT(SECOND FROM SYSTIMESTAMP);
-- START MIERZENIA CZASU

SELECT * FROM CITIES c WHERE CITY IN (
	'Madrid',
	'NYC',
	'Auckland',
	'Paris',
	'Singapore'
);


VARIABLE  TIME_FOR_EKS1_SQL NUMBER;
EXEC :TIME_FOR_EKS1_SQL := EXTRACT(SECOND FROM SYSTIMESTAMP)-:START_TIME_EKS1_SQL;
spool eksperyment1_sql.txt append;
PRINT TIME_FOR_EKS1_SQL;
spool off;