-- FLUSH 
ALTER SYSTEM FLUSH buffer_cache;
ALTER SYSTEM FLUSH shared_pool;

VARIABLE  START_TIME_EKS1_SDO NUMBER;
EXEC :START_TIME_EKS1_SDO := EXTRACT(SECOND FROM SYSTIMESTAMP);
-- START MIERZENIA CZASU

-- MADRID
SELECT cu.* FROM CUSTOMERS cu
JOIN CITIES ci ON cu.CITY = ci.CITY
WHERE SDO_EQUAL(ci.LOCATION, SDO_GEOMETRY(2001,NULL, SDO_POINT_TYPE(4.732445,-74.264192, NULL),NULL,NULL)) = 'TRUE';

-- NYC
SELECT cu.* FROM CUSTOMERS cu
JOIN CITIES ci ON cu.CITY = ci.CITY
WHERE SDO_EQUAL(ci.LOCATION, SDO_GEOMETRY(2001,NULL, SDO_POINT_TYPE(31.2177778,-88.3905556, NULL),NULL,NULL)) = 'TRUE';

-- Auckland
SELECT cu.* FROM CUSTOMERS cu
JOIN CITIES ci ON cu.CITY = ci.CITY
WHERE SDO_EQUAL(ci.LOCATION, SDO_GEOMETRY(2001,NULL, SDO_POINT_TYPE(-36.866667,174.766667, NULL),NULL,NULL)) = 'TRUE';

-- Paris
SELECT cu.* FROM CUSTOMERS cu
JOIN CITIES ci ON cu.CITY = ci.CITY
WHERE SDO_EQUAL(ci.LOCATION, SDO_GEOMETRY(2001,NULL, SDO_POINT_TYPE(-13.55,-62.4833333, NULL),NULL,NULL)) = 'TRUE';

-- Singapore
SELECT cu.* FROM CUSTOMERS cu
JOIN CITIES ci ON cu.CITY = ci.CITY
WHERE SDO_EQUAL(ci.LOCATION, SDO_GEOMETRY(2001,NULL, SDO_POINT_TYPE(1.2930556,103.8558333, NULL),NULL,NULL)) = 'TRUE';



VARIABLE  TIME_FOR_EKS1_SDO NUMBER;
EXEC :TIME_FOR_EKS1_SDO := EXTRACT(SECOND FROM SYSTIMESTAMP)-:START_TIME_EKS1_SDO;
spool eksperyment1_sdo.txt append;
PRINT TIME_FOR_EKS1_SDO;
spool off;