CREATE TABLE "CITIES"
(  
	"CITY" VARCHAR2(50) NOT NULL ENABLE,
	"LOCATION" ST_GEOMETRY,
	 PRIMARY KEY ("CITY")
);

ALTER TABLE PRODUCTS 
ADD RECTANGLE ST_GEOMETRY;

ALTER TABLE ORDERS 
ADD RECTANGLE ST_GEOMETRY;

ALTER TABLE OFFICES 
ADD CONSTRAINT FK_OFFICES_CITIES
   FOREIGN KEY (CITY)
   REFERENCES CITIES (CITY);
   
   
ALTER TABLE CUSTOMERS 
ADD CONSTRAINT FK_CUSTOMERS_CITIES
   FOREIGN KEY (CITY)
   REFERENCES CITIES (CITY);