CREATE TABLE "CITIES"
(  
	"CITY" VARCHAR2(50) NOT NULL ENABLE,
	"LOCATION" MDSYS.SDO_GEOMETRY,
	 PRIMARY KEY ("CITY")
);

ALTER TABLE PRODUCTS 
ADD RECTANGLE MDSYS.SDO_GEOMETRY;

ALTER TABLE ORDERS 
ADD SHIPPINGPATH MDSYS.SDO_GEOMETRY;
