ALTER TABLE OFFICES 
ADD CONSTRAINT FK_OFFICES_CITIES
   FOREIGN KEY (CITY)
   REFERENCES CITIES(CITY);   
   
ALTER TABLE CUSTOMERS 
ADD CONSTRAINT FK_CUSTOMERS_CITIES
   FOREIGN KEY (CITY)
   REFERENCES CITIES(CITY);