--1



--2
DELETE FROM ORDERS ORD
WHERE ORD.ORDERNUMBER IN (SELECT ORDNUM FROM (SELECT ORD.ORDERNUMBER AS ORDNUM, SDO_GEOM.SDO_Length(ORD.RECTANGLE) AS LINELENGHT  FROM ORDERS ORD
ORDER BY LINELENGHT)
WHERE LINELENGHT < 20);

--3

--4

--5
SELECT DISTINCT(CST.CUSTOMERNUMBER), CST.CITY, OFC.CITY FROM CUSTOMERS CST
INNER JOIN EMPLOYEES EMP ON CST.SALESREPEMPLOYEENUMBER = EMP.EMPLOYEENUMBER
INNER JOIN OFFICES OFC ON EMP.OFFICECODE = OFC.OFFICECODE
INNER JOIN CITIES CTS ON CST.CITY = CTS.CITY
INNER JOIN CITIES CTS1 ON CTS.CITY = OFC.CITY
WHERE SDO_EQUAL(CTS.LOCATION, CTS1.LOCATION) = 'TRUE'
ORDER BY CST.CITY;

--6

--7
