--DANE PRZESTRZENNE
-- FLUSH 
ALTER SYSTEM FLUSH buffer_cache;
ALTER SYSTEM FLUSH shared_pool;

VARIABLE  START_TIME_PR NUMBER;
EXEC :START_TIME_PR := EXTRACT(SECOND FROM SYSTIMESTAMP);
-- START MIERZENIA CZASU


--4
SELECT cu.* FROM CUSTOMERS cu
JOIN CITIES ci ON cu.CITY = ci.CITY 
WHERE SDO_EQUAL(ci.LOCATION, SDO_GEOMETRY(2001,NULL, SDO_POINT_TYPE(4.732445,-74.264192, NULL),NULL,NULL)) = 'TRUE';SELECT * FROM CUSTOMERS c WHERE CITY = 'Madrid'

--5
SELECT DISTINCT(CST.CUSTOMERNUMBER), CST.CITY, OFC.CITY FROM CUSTOMERS CST
INNER JOIN EMPLOYEES EMP ON CST.SALESREPEMPLOYEENUMBER = EMP.EMPLOYEENUMBER
INNER JOIN OFFICES OFC ON EMP.OFFICECODE = OFC.OFFICECODE
INNER JOIN CITIES CTS ON CST.CITY = CTS.CITY
INNER JOIN CITIES CTS1 ON CTS.CITY = OFC.CITY
WHERE SDO_EQUAL(CTS.LOCATION, CTS1.LOCATION) = 'TRUE'
ORDER BY CST.CITY;


VARIABLE  TIME_FOR_PR NUMBER;
EXEC :TIME_FOR_PR := EXTRACT(SECOND FROM SYSTIMESTAMP)-:START_TIME_PR;
spool etap4_results.txt append;
PRINT TIME_FOR_PR;
spool off;
ROLLBACK;