--1
SELECT * FROM CITIES c WHERE c.CITY = 'Wrocław'

--2
SELECT ORDNUM, LINELENGHT FROM (SELECT ORD.ORDERNUMBER AS ORDNUM, SDO_GEOM.SDO_Length(ORD.RECTANGLE) AS LINELENGHT  FROM ORDERS ORD
ORDER BY LINELENGHT)
WHERE LINELENGHT < 20;

--3

--4
SELECT * FROM CUSTOMERS c WHERE CITY = 'Madrid'


--5
SELECT CST.CUSTOMERNUMBER, CST.CITY, OFC.CITY FROM CUSTOMERS CST
INNER JOIN EMPLOYEES EMP ON CST.SALESREPEMPLOYEENUMBER = EMP.EMPLOYEENUMBER
INNER JOIN OFFICES OFC ON EMP.OFFICECODE = OFC.OFFICECODE
WHERE OFC.CITY = CST.CITY
ORDER BY CST.CITY;
--6

--7
SELECT ORD.ORDERNUMBER,  ORDD.QUANTITYORDERED, PRD.PRODUCTCODE,SDO_GEOM.SDO_AREA(PRD.RECTANGLE, 0.005), PRD.RECTANGLE.Get_WKT() FROM ORDERS ORD
INNER JOIN ORDERDETAILS ORDD ON ORDD.ORDERNUMBER = ORD.ORDERNUMBER
INNER JOIN PRODUCTS PRD ON PRD.PRODUCTCODE = ORDD.PRODUCTCODE
WHERE ORD.CUSTOMERNUMBER = 103
ORDER BY ORD.ORDERNUMBER;


SELECT PRD.PRODUCTCODE, SDO_GEOM.SDO_AREA(PRD.RECTANGLE, 0.005), PRD.RECTANGLE.Get_WKT() FROM PRODUCTS PRD;