--1

--2
SELECT ORDNUM, LINELENGHT FROM (SELECT ORD.ORDERNUMBER AS ORDNUM, SDO_GEOM.SDO_Length(ORD.RECTANGLE) AS LINELENGHT  FROM ORDERS ORD
ORDER BY LINELENGHT)
WHERE LINELENGHT < 20;

--3

--4

--5
SELECT CST.CUSTOMERNUMBER, CST.CITY, OFC.CITY FROM CUSTOMERS CST
INNER JOIN EMPLOYEES EMP ON CST.SALESREPEMPLOYEENUMBER = EMP.EMPLOYEENUMBER
INNER JOIN OFFICES OFC ON EMP.OFFICECODE = OFC.OFFICECODE
WHERE OFC.CITY = CST.CITY
ORDER BY CST.CITY;
--6

--7
