--Crud
-- FLUSH 
ALTER SYSTEM FLUSH buffer_cache;
ALTER SYSTEM FLUSH shared_pool;

VARIABLE  START_TIME_CRUD NUMBER;
EXEC :START_TIME_CRUD := EXTRACT(SECOND FROM SYSTIMESTAMP);
-- START MIERZENIA CZASU


--4
SELECT * FROM CUSTOMERS c WHERE CITY = 'Madrid'

--5
SELECT CST.CUSTOMERNUMBER, CST.CITY, OFC.CITY FROM CUSTOMERS CST
INNER JOIN EMPLOYEES EMP ON CST.SALESREPEMPLOYEENUMBER = EMP.EMPLOYEENUMBER
INNER JOIN OFFICES OFC ON EMP.OFFICECODE = OFC.OFFICECODE
WHERE OFC.CITY = CST.CITY
ORDER BY CST.CITY;


VARIABLE  TIME_FOR_CRUD NUMBER;
EXEC :TIME_FOR_CRUD := EXTRACT(SECOND FROM SYSTIMESTAMP)-:START_TIME_CRUD;
spool etap4_results.txt append;
PRINT TIME_FOR_CRUD;
spool off;
ROLLBACK;