-- FLUSH 
ALTER SYSTEM FLUSH buffer_cache;
ALTER SYSTEM FLUSH shared_pool;

VARIABLE  START_TIME_ZESTAW_A NUMBER;
EXEC :START_TIME_ZESTAW_A := EXTRACT(SECOND FROM SYSTIMESTAMP);
-- START MIERZENIA CZASU


--1 
SELECT SUM(OD.PRICEEACH * OD.QUANTITYORDERED) FROM ORDERDETAILS OD 
INNER JOIN ORDERS O ON OD.ORDERNUMBER = O.ORDERNUMBER
WHERE O.ORDERDATE >= to_date('2003-04-01','YYYY-MM-DD') 
AND O.ORDERDATE <to_date('2003-05-01','YYYY-MM-DD'); 

--2
SELECT SUM(OD.PRICEEACH * OD.QUANTITYORDERED), CUSTOMERS.CONTACTLASTNAME FROM ORDERDETAILS OD 
INNER JOIN ORDERS O ON OD.ORDERNUMBER = O.ORDERNUMBER
INNER JOIN CUSTOMERS ON CUSTOMERS.CUSTOMERNUMBER = O.CUSTOMERNUMBER
WHERE O.ORDERDATE >= to_date('2003-04-01','YYYY-MM-DD') 
AND O.ORDERDATE <to_date('2003-05-01','YYYY-MM-DD') 
GROUP BY CUSTOMERS.CONTACTLASTNAME;



--3
SELECT ORD.ORDERNUMBER, SUM(OD.QUANTITYORDERED * (OD.PRICEEACH - PD.MSRP)) AS PRICE FROM ORDERS ORD
INNER JOIN ORDERDETAILS OD ON OD.ORDERNUMBER = ORD.ORDERNUMBER
INNER JOIN PRODUCTS PD ON PD.PRODUCTCODE = OD.PRODUCTCODE
WHERE ORD.ORDERDATE >= to_date('2003-04-01','YYYY-MM-DD') 
AND ORD.ORDERDATE <to_date('2003-05-01','YYYY-MM-DD')
GROUP BY ORD.ORDERNUMBER
ORDER BY PRICE;


--4 PROBLEM
SELECT * FROM (SELECT (SUMACTS - PARAGON) AS ZADLUZENIE, CSTN  FROM (SELECT SUM(SUMA) AS SUMACTS, CSTN FROM (SELECT SUM(ORD.PRICEEACH*ORD.QUANTITYORDERED) AS SUMA , ORD.ORDERNUMBER AS ORDN, CST.CUSTOMERNUMBER AS CSTN  FROM ORDERDETAILS ORD
INNER JOIN ORDERS ORS ON ORS.ORDERNUMBER = ORD.ORDERNUMBER
INNER JOIN CUSTOMERS CST ON ORS.CUSTOMERNUMBER = CST.CUSTOMERNUMBER
GROUP BY ORD.ORDERNUMBER,CST.CUSTOMERNUMBER
ORDER BY CST.CUSTOMERNUMBER )
GROUP BY CSTN
ORDER BY CSTN)  
INNER JOIN CUSTOMERS CST ON CST.CUSTOMERNUMBER = CSTN
INNER JOIN (SELECT SUM(PMN.AMOUNT) AS PARAGON, PMN.CUSTOMERNUMBER AS PCSTN FROM PAYMENTS PMN 
INNER JOIN CUSTOMERS CUST ON PMN.CUSTOMERNUMBER = CUST.CUSTOMERNUMBER
GROUP BY PMN.CUSTOMERNUMBER) ON PCSTN = CST.CUSTOMERNUMBER)
WHERE ZADLUZENIE > 0;


--5
insert  into payments(customerNumber,checkNumber,paymentDate,amount) values (103,'HQR336331',to_date('2020-02-19','YYYY-MM-DD'),6066.78);
insert  into payments(customerNumber,checkNumber,paymentDate,amount) values (103,'HQR336332',to_date('2020-02-19','YYYY-MM-DD'),6066.78);
insert  into payments(customerNumber,checkNumber,paymentDate,amount) values (103,'HQR336333',to_date('2020-02-19','YYYY-MM-DD'),6066.78);
insert  into payments(customerNumber,checkNumber,paymentDate,amount) values (103,'HQR336334',to_date('2020-02-19','YYYY-MM-DD'),6066.78);
insert  into payments(customerNumber,checkNumber,paymentDate,amount) values (103,'HQR336335',to_date('2020-02-19','YYYY-MM-DD'),6066.78);
insert  into payments(customerNumber,checkNumber,paymentDate,amount) values (103,'HQR336336',to_date('2020-02-19','YYYY-MM-DD'),6066.78);
insert  into payments(customerNumber,checkNumber,paymentDate,amount) values (103,'HQR336337',to_date('2020-02-19','YYYY-MM-DD'),6066.78);
insert  into payments(customerNumber,checkNumber,paymentDate,amount) values (103,'HQR336338',to_date('2020-02-19','YYYY-MM-DD'),6066.78);
insert  into payments(customerNumber,checkNumber,paymentDate,amount) values (103,'HQR336339',to_date('2020-02-19','YYYY-MM-DD'),6066.78);
insert  into payments(customerNumber,checkNumber,paymentDate,amount) values (103,'HQR236331',to_date('2020-02-19','YYYY-MM-DD'),6066.78);
insert  into payments(customerNumber,checkNumber,paymentDate,amount) values (103,'HQR236332',to_date('2020-02-19','YYYY-MM-DD'),6066.78);
insert  into payments(customerNumber,checkNumber,paymentDate,amount) values (103,'HQR236333',to_date('2020-02-19','YYYY-MM-DD'),6066.78);
insert  into payments(customerNumber,checkNumber,paymentDate,amount) values (103,'HQR236334',to_date('2020-02-19','YYYY-MM-DD'),6066.78);
insert  into payments(customerNumber,checkNumber,paymentDate,amount) values (103,'HQR236335',to_date('2020-02-19','YYYY-MM-DD'),6066.78);


--6
DELETE FROM PAYMENTS PMN
WHERE PMN.PAYMENTDATE = to_date('2020-02-19','YYYY-MM-DD');

--7
UPDATE ORDERS ORD
SET ORD.STATUS = 'Delivered',
ORD.SHIPPEDDATE = to_date('2005-06-04','YYYY-MM-DD') 
WHERE ORD.STATUS = 'In Process';


--8
UPDATE ORDERS ORD
SET ORD.STATUS = 'Delivered',
ORD.COMMENTS = 'A TU JEST NOWY, MOZE DLUGI KOMENTAZ, ALE TAKI POTRZEBNY ZEBY CZAS BYL WIEKSZY'
WHERE ORD.STATUS = 'Shipped'
AND ORD.COMMENTS IS NULL;


VARIABLE  TIME_FOR_ZESTAW_A NUMBER;
EXEC :TIME_FOR_ZESTAW_A := EXTRACT(SECOND FROM SYSTIMESTAMP)-:START_TIME_ZESTAW_A;

spool etap1_results.txt append;
PRINT TIME_FOR_ZESTAW_A;
spool off;