-- FLUSH 
ALTER SYSTEM FLUSH buffer_cache;
ALTER SYSTEM FLUSH shared_pool;

VARIABLE  START_TIME_P10 NUMBER;
EXEC :START_TIME_P10 := EXTRACT(SECOND FROM SYSTIMESTAMP);
-- START MIERZENIA CZASU

SELECT TP.LOGID, SDO_GEOM.SDO_Length(TP.LINE) AS LINELENGHT  
FROM TENPOINTS TP
ORDER BY LINELENGHT;

VARIABLE  TIME_FOR_P10 NUMBER;
EXEC :TIME_FOR_P10 := EXTRACT(SECOND FROM SYSTIMESTAMP)-:START_TIME_P10;
spool eksperyment_results.txt append;
PRINT TIME_FOR_P10;
spool off;
ROLLBACK;