--tabale do eksperymentu
--1
CREATE TABLE "TWOPOINTS"
(  
	LogID int GENERATED ALWAYS AS IDENTITY,
	Line MDSYS.SDO_GEOMETRY	 
);

--2
CREATE TABLE "FIVEPOINTS"
(  
	LogID int GENERATED ALWAYS AS IDENTITY,
	Line MDSYS.SDO_GEOMETRY	 
);

--3
CREATE TABLE "TENPOINTS"
(  
	LogID int GENERATED ALWAYS AS IDENTITY,
	Line MDSYS.SDO_GEOMETRY	 
);