-- FLUSH 
ALTER SYSTEM FLUSH buffer_cache;
ALTER SYSTEM FLUSH shared_pool;

VARIABLE  START_TIME_P2 NUMBER;
EXEC :START_TIME_P2 := EXTRACT(SECOND FROM SYSTIMESTAMP);
-- START MIERZENIA CZASU

SELECT TW.LOGID, SDO_GEOM.SDO_Length(TW.LINE) AS LINELENGHT  
FROM TWOPOINTS TW
ORDER BY LINELENGHT;

VARIABLE  TIME_FOR_P2 NUMBER;
EXEC :TIME_FOR_P2 := EXTRACT(SECOND FROM SYSTIMESTAMP)-:START_TIME_P2;
spool eksperyment_results.txt append;
PRINT TIME_FOR_P2;
spool off;
ROLLBACK;