-- FLUSH 
ALTER SYSTEM FLUSH buffer_cache;
ALTER SYSTEM FLUSH shared_pool;

VARIABLE  START_TIME_P5 NUMBER;
EXEC :START_TIME_P5 := EXTRACT(SECOND FROM SYSTIMESTAMP);
-- START MIERZENIA CZASU

SELECT FP.LOGID, SDO_GEOM.SDO_Length(FP.LINE) AS LINELENGHT  
FROM FIVEPOINTS FP
ORDER BY LINELENGHT;

VARIABLE  TIME_FOR_P5 NUMBER;
EXEC :TIME_FOR_P5 := EXTRACT(SECOND FROM SYSTIMESTAMP)-:START_TIME_P5;
spool eksperyment_results.txt append;
PRINT TIME_FOR_P5;
spool off;
ROLLBACK;