--SELECTY
--1. Zarobek wygenerowany z zamówień przez wybranego pracownika

SELECT EMPLOYEENUMBER, SUM(EARNED) AS EARNED FROM CUSTOMERS cu INNER JOIN (
SELECT SUM(EARNED) AS EARNED, CUSTOMERNUMBER FROM ORDERS o INNER JOIN (
SELECT SUM(EARNED) AS EARNED, ORDERNUMBER FROM(
SELECT (PRICEEACH * QUANTITYORDERED) - (BUYPRICE * QUANTITYORDERED) AS EARNED, ORDERNUMBER FROM (
SELECT * FROM PRODUCTS p INNER JOIN ORDERDETAILS od ON od.PRODUCTCODE = p.PRODUCTCODE) a ORDER BY ORDERNUMBER ) b GROUP BY ORDERNUMBER ) c ON o.ORDERNUMBER  = c.ORDERNUMBER GROUP BY CUSTOMERNUMBER ORDER BY CUSTOMERNUMBER) d ON d.CUSTOMERNUMBER = cu.CUSTOMERNUMBER
RIGHT JOIN EMPLOYEES e ON cu.SALESREPEMPLOYEENUMBER = e.EMPLOYEENUMBER WHERE EMPLOYEENUMBER = 1216 GROUP BY EMPLOYEENUMBER ORDER BY EMPLOYEENUMBER ;

--2. Który pracownik miał największą różnicę pomiędzy najdroższym a najtańszym produktem
SELECT MAX(DIFFERENCE), EMPLOYEENUMBER FROM (
SELECT MAX(BUYPRICE) - MIN(BUYPRICE) AS DIFFERENCE, EMPLOYEENUMBER FROM (
SELECT e.EMPLOYEENUMBER, o.ORDERNUMBER, QUANTITYORDERED, PRICEEACH, p.PRODUCTNAME, p.BUYPRICE FROM EMPLOYEES e INNER JOIN CUSTOMERS c ON c.SALESREPEMPLOYEENUMBER = e.EMPLOYEENUMBER INNER JOIN ORDERS o ON o.CUSTOMERNUMBER  = c.CUSTOMERNUMBER INNER JOIN ORDERDETAILS od ON od.ORDERNUMBER = o.ORDERNUMBER INNER JOIN PRODUCTS p ON p.PRODUCTCODE = od.PRODUCTCODE) a
GROUP BY ORDERNUMBER, EMPLOYEENUMBER) b GROUP BY EMPLOYEENUMBER ORDER BY MAX(DIFFERENCE);

--3. Ilu pracowników ma dane stanowisko

SELECT COUNT(*) FROM EMPLOYEES e GROUP BY JOBTITLE;

--4. Z którego kraju klient zrobił najdroższe zamówienie

--5. Który pracownik ma najwięcej klientów


--CRUDY
--6. Przeniesienia pracownika do innego biura

--7. Zmiana pracownika odpowiedzialnego za daną grupę klientów

--8. Zmniejszenie limitu kredytowego o 10% dla klientów którzy w wybranym miesiącu zrobili zamówienie na kwotę mniej niż 1000
