--Crud_1
-- FLUSH 
ALTER SYSTEM FLUSH buffer_cache;
ALTER SYSTEM FLUSH shared_pool;

VARIABLE  START_TIME_CRUD_1 NUMBER;
EXEC :START_TIME_CRUD_1 := EXTRACT(SECOND FROM SYSTIMESTAMP);
-- START MIERZENIA CZASU

UPDATE ORDERS ORD
SET ORD.STATUS = 'On Road',
ORD.REQUIREDDATE = ORD.REQUIREDDATE +1
WHERE ORD.ORDERNUMBER = 10420;

UPDATE ORDERS ORD
SET ORD.STATUS = 'On Road',
ORD.REQUIREDDATE = ORD.REQUIREDDATE +1
WHERE ORD.ORDERNUMBER = 10421;

UPDATE ORDERS ORD
SET ORD.STATUS = 'On Road',
ORD.REQUIREDDATE = ORD.REQUIREDDATE +1
WHERE ORD.ORDERNUMBER = 10422;

UPDATE ORDERS ORD
SET ORD.STATUS = 'On Road',
ORD.REQUIREDDATE = ORD.REQUIREDDATE +1
WHERE ORD.ORDERNUMBER = 10423;


UPDATE ORDERS ORD
SET ORD.STATUS = 'On Road',
ORD.REQUIREDDATE = ORD.REQUIREDDATE +1
WHERE ORD.ORDERNUMBER = 10424;

VARIABLE  TIME_FOR_CRUD_1 NUMBER;
EXEC :TIME_FOR_CRUD_1 := EXTRACT(SECOND FROM SYSTIMESTAMP)-:START_TIME_CRUD_1;
spool etap2_results.txt append;
PRINT TIME_FOR_CRUD_1;
spool off;
ROLLBACK;