	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>
	<payment>
		<customerNumber>103</customerNumber>
        <checkNumber>HQ336336</checkNumber>
        <paymentDate>19.10.2004</paymentDate>
        <amount>6066,78</amount>
	</payment>');
	
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>
	<payment>
		<customerNumber>103</customerNumber>
        <checkNumber>JM555205</checkNumber>
        <paymentDate>05.06.2003</paymentDate>
        <amount>14571,44</amount>
	</payment>');
	
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>
	<payment>
		<customerNumber>103</customerNumber>
        <checkNumber>OM314933</checkNumber>
        <paymentDate>18.12.2004</paymentDate>
        <amount>1676,14</amount>
	</payment>');
	
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>
	payment>
		<customerNumber>112</customerNumber>
        <checkNumber>BO864823</checkNumber>
        <paymentDate>17.12.2004</paymentDate>
        <amount>14191,12</amount>
	</payment>');
	
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>
	<payment>
		<customerNumber>112</customerNumber>
        <checkNumber>HQ55022</checkNumber>
        <paymentDate>06.06.2003</paymentDate>
        <amount>32641,98</amount>
	</payment>');
	
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>
	<payment>
		<customerNumber>112</customerNumber>
        <checkNumber>ND748579</checkNumber>
        <paymentDate>20.08.2004</paymentDate>
        <amount>33347,88</amount>
	</payment>');
	
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>
	<payment>
		<customerNumber>114</customerNumber>
        <checkNumber>GG31455</checkNumber>
        <paymentDate>20.05.2003</paymentDate>
        <amount>45864,03</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>114</customerNumber>
        <checkNumber>MA765515</checkNumber>
        <paymentDate>15.12.2004</paymentDate>
        <amount>82261,22</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>114</customerNumber>
        <checkNumber>NP603840</checkNumber>
        <paymentDate>31.05.2003</paymentDate>
        <amount>7565,08</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>114</customerNumber>
        <checkNumber>NR27552</checkNumber>
        <paymentDate>10.03.2004</paymentDate>
        <amount>44894,74</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>119</customerNumber>
        <checkNumber>DB933704</checkNumber>
        <paymentDate>14.11.2004</paymentDate>
        <amount>19501,82</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>119</customerNumber>
        <checkNumber>LN373447</checkNumber>
        <paymentDate>08.08.2004</paymentDate>
        <amount>47924,19</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>119</customerNumber>
        <checkNumber>NG94694</checkNumber>
        <paymentDate>22.02.2005</paymentDate>
        <amount>49523,67</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>121</customerNumber>
        <checkNumber>DB889831</checkNumber>
        <paymentDate>16.02.2003</paymentDate>
        <amount>50218,95</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>121</customerNumber>
        <checkNumber>FD317790</checkNumber>
        <paymentDate>28.10.2003</paymentDate>
        <amount>1491,38</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>121</customerNumber>
        <checkNumber>KI831359</checkNumber>
        <paymentDate>04.11.2004</paymentDate>
        <amount>17876,32</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>121</customerNumber>
        <checkNumber>MA302151</checkNumber>
        <paymentDate>28.11.2004</paymentDate>
        <amount>34638,14</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>124</customerNumber>
        <checkNumber>AE215433</checkNumber>
        <paymentDate>05.03.2005</paymentDate>
        <amount>101244,59</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>124</customerNumber>
        <checkNumber>BG255406</checkNumber>
        <paymentDate>28.08.2004</paymentDate>
        <amount>85410,87</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>124</customerNumber>
        <checkNumber>CQ287967</checkNumber>
        <paymentDate>11.04.2003</paymentDate>
        <amount>11044,3</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>124</customerNumber>
        <checkNumber>ET64396</checkNumber>
        <paymentDate>16.04.2005</paymentDate>
        <amount>83598,04</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>124</customerNumber>
        <checkNumber>HI366474</checkNumber>
        <paymentDate>27.12.2004</paymentDate>
        <amount>47142,7</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>124</customerNumber>
        <checkNumber>HR86578</checkNumber>
        <paymentDate>02.11.2004</paymentDate>
        <amount>55639,66</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>124</customerNumber>
        <checkNumber>KI131716</checkNumber>
        <paymentDate>15.08.2003</paymentDate>
        <amount>111654,4</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>124</customerNumber>
        <checkNumber>LF217299</checkNumber>
        <paymentDate>26.03.2004</paymentDate>
        <amount>43369,3</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>124</customerNumber>
        <checkNumber>NT141748</checkNumber>
        <paymentDate>25.11.2003</paymentDate>
        <amount>45084,38</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>128</customerNumber>
        <checkNumber>DI925118</checkNumber>
        <paymentDate>28.01.2003</paymentDate>
        <amount>10549,01</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>128</customerNumber>
        <checkNumber>FA465482</checkNumber>
        <paymentDate>18.10.2003</paymentDate>
        <amount>24101,81</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>128</customerNumber>
        <checkNumber>FH668230</checkNumber>
        <paymentDate>24.03.2004</paymentDate>
        <amount>33820,62</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>128</customerNumber>
        <checkNumber>IP383901</checkNumber>
        <paymentDate>18.11.2004</paymentDate>
        <amount>7466,32</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>129</customerNumber>
        <checkNumber>DM826140</checkNumber>
        <paymentDate>08.12.2004</paymentDate>
        <amount>26248,78</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>129</customerNumber>
        <checkNumber>ID449593</checkNumber>
        <paymentDate>11.12.2003</paymentDate>
        <amount>23923,93</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>129</customerNumber>
        <checkNumber>PI42991</checkNumber>
        <paymentDate>09.04.2003</paymentDate>
        <amount>16537,85</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>131</customerNumber>
        <checkNumber>CL442705</checkNumber>
        <paymentDate>12.03.2003</paymentDate>
        <amount>22292,62</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>131</customerNumber>
        <checkNumber>MA724562</checkNumber>
        <paymentDate>02.12.2004</paymentDate>
        <amount>50025,35</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>131</customerNumber>
        <checkNumber>NB445135</checkNumber>
        <paymentDate>11.09.2004</paymentDate>
        <amount>35321,97</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>141</customerNumber>
        <checkNumber>AU364101</checkNumber>
        <paymentDate>19.07.2003</paymentDate>
        <amount>36251,03</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>141</customerNumber>
        <checkNumber>DB583216</checkNumber>
        <paymentDate>01.11.2004</paymentDate>
        <amount>36140,38</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>141</customerNumber>
        <checkNumber>DL460618</checkNumber>
        <paymentDate>19.05.2005</paymentDate>
        <amount>46895,48</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>141</customerNumber>
        <checkNumber>HJ32686</checkNumber>
        <paymentDate>30.01.2004</paymentDate>
        <amount>59830,55</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>141</customerNumber>
        <checkNumber>ID10962</checkNumber>
        <paymentDate>31.12.2004</paymentDate>
        <amount>116208,4</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>141</customerNumber>
        <checkNumber>IN446258</checkNumber>
        <paymentDate>25.03.2005</paymentDate>
        <amount>65071,26</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>141</customerNumber>
        <checkNumber>JE105477</checkNumber>
        <paymentDate>18.03.2005</paymentDate>
        <amount>120166,58</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>141</customerNumber>
        <checkNumber>JN355280</checkNumber>
        <paymentDate>26.10.2003</paymentDate>
        <amount>49539,37</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>141</customerNumber>
        <checkNumber>JN722010</checkNumber>
        <paymentDate>25.02.2003</paymentDate>
        <amount>40206,2</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>141</customerNumber>
        <checkNumber>KT52578</checkNumber>
        <paymentDate>09.12.2003</paymentDate>
        <amount>63843,55</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>141</customerNumber>
        <checkNumber>MC46946</checkNumber>
        <paymentDate>09.07.2004</paymentDate>
        <amount>35420,74</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>141</customerNumber>
        <checkNumber>MF629602</checkNumber>
        <paymentDate>16.08.2004</paymentDate>
        <amount>20009,53</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>141</customerNumber>
        <checkNumber>NU627706</checkNumber>
        <paymentDate>17.05.2004</paymentDate>
        <amount>26155,91</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>144</customerNumber>
        <checkNumber>IR846303</checkNumber>
        <paymentDate>12.12.2004</paymentDate>
        <amount>36005,71</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>144</customerNumber>
        <checkNumber>LA685678</checkNumber>
        <paymentDate>09.04.2003</paymentDate>
        <amount>7674,94</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>145</customerNumber>
        <checkNumber>CN328545</checkNumber>
        <paymentDate>03.07.2004</paymentDate>
        <amount>4710,73</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>145</customerNumber>
        <checkNumber>ED39322</checkNumber>
        <paymentDate>26.04.2004</paymentDate>
        <amount>28211,7</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>145</customerNumber>
        <checkNumber>HR182688</checkNumber>
        <paymentDate>01.12.2004</paymentDate>
        <amount>20564,86</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>145</customerNumber>
        <checkNumber>JJ246391</checkNumber>
        <paymentDate>20.02.2003</paymentDate>
        <amount>53959,21</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>146</customerNumber>
        <checkNumber>FP549817</checkNumber>
        <paymentDate>18.03.2004</paymentDate>
        <amount>40978,53</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>146</customerNumber>
        <checkNumber>FU793410</checkNumber>
        <paymentDate>16.01.2004</paymentDate>
        <amount>49614,72</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>146</customerNumber>
        <checkNumber>LJ160635</checkNumber>
        <paymentDate>10.12.2003</paymentDate>
        <amount>39712,1</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>148</customerNumber>
        <checkNumber>BI507030</checkNumber>
        <paymentDate>22.04.2003</paymentDate>
        <amount>44380,15</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>148</customerNumber>
        <checkNumber>DD635282</checkNumber>
        <paymentDate>11.08.2004</paymentDate>
        <amount>2611,84</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>148</customerNumber>
        <checkNumber>KM172879</checkNumber>
        <paymentDate>26.12.2003</paymentDate>
        <amount>105743</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>148</customerNumber>
        <checkNumber>ME497970</checkNumber>
        <paymentDate>27.03.2005</paymentDate>
        <amount>3516,04</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>151</customerNumber>
        <checkNumber>BF686658</checkNumber>
        <paymentDate>22.12.2003</paymentDate>
        <amount>58793,53</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>151</customerNumber>
        <checkNumber>GB852215</checkNumber>
        <paymentDate>26.07.2004</paymentDate>
        <amount>20314,44</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>151</customerNumber>
        <checkNumber>IP568906</checkNumber>
        <paymentDate>18.06.2003</paymentDate>
        <amount>58841,35</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>151</customerNumber>
        <checkNumber>KI884577</checkNumber>
        <paymentDate>14.12.2004</paymentDate>
        <amount>39964,63</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>157</customerNumber>
        <checkNumber>HI618861</checkNumber>
        <paymentDate>19.11.2004</paymentDate>
        <amount>35152,12</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>157</customerNumber>
        <checkNumber>NN711988</checkNumber>
        <paymentDate>07.09.2004</paymentDate>
        <amount>63357,13</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>161</customerNumber>
        <checkNumber>BR352384</checkNumber>
        <paymentDate>14.11.2004</paymentDate>
        <amount>2434,25</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>161</customerNumber>
        <checkNumber>BR478494</checkNumber>
        <paymentDate>18.11.2003</paymentDate>
        <amount>50743,65</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>161</customerNumber>
        <checkNumber>KG644125</checkNumber>
        <paymentDate>02.02.2005</paymentDate>
        <amount>12692,19</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>161</customerNumber>
        <checkNumber>NI908214</checkNumber>
        <paymentDate>05.08.2003</paymentDate>
        <amount>38675,13</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>166</customerNumber>
        <checkNumber>BQ327613</checkNumber>
        <paymentDate>16.09.2004</paymentDate>
        <amount>38785,48</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>166</customerNumber>
        <checkNumber>DC979307</checkNumber>
        <paymentDate>07.07.2004</paymentDate>
        <amount>44160,92</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>166</customerNumber>
        <checkNumber>LA318629</checkNumber>
        <paymentDate>28.02.2004</paymentDate>
        <amount>22474,17</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>167</customerNumber>
        <checkNumber>ED743615</checkNumber>
        <paymentDate>19.09.2004</paymentDate>
        <amount>12538,01</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>167</customerNumber>
        <checkNumber>GN228846</checkNumber>
        <paymentDate>03.12.2003</paymentDate>
        <amount>85024,46</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>171</customerNumber>
        <checkNumber>GB878038</checkNumber>
        <paymentDate>15.03.2004</paymentDate>
        <amount>18997,89</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>171</customerNumber>
        <checkNumber>IL104425</checkNumber>
        <paymentDate>22.11.2003</paymentDate>
        <amount>42783,81</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>172</customerNumber>
        <checkNumber>AD832091</checkNumber>
        <paymentDate>09.09.2004</paymentDate>
        <amount>1960,8</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>172</customerNumber>
        <checkNumber>CE51751</checkNumber>
        <paymentDate>04.12.2004</paymentDate>
        <amount>51209,58</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>172</customerNumber>
        <checkNumber>EH208589</checkNumber>
        <paymentDate>20.04.2003</paymentDate>
        <amount>33383,14</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>173</customerNumber>
        <checkNumber>GP545698</checkNumber>
        <paymentDate>13.05.2004</paymentDate>
        <amount>11843,45</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>173</customerNumber>
        <checkNumber>IG462397</checkNumber>
        <paymentDate>29.03.2004</paymentDate>
        <amount>20355,24</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>175</customerNumber>
        <checkNumber>CITI3434344</checkNumber>
        <paymentDate>19.05.2005</paymentDate>
        <amount>28500,78</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>175</customerNumber>
        <checkNumber>IO448913</checkNumber>
        <paymentDate>19.11.2003</paymentDate>
        <amount>24879,08</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>175</customerNumber>
        <checkNumber>PI15215</checkNumber>
        <paymentDate>10.07.2004</paymentDate>
        <amount>42044,77</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>177</customerNumber>
        <checkNumber>AU750837</checkNumber>
        <paymentDate>17.04.2004</paymentDate>
        <amount>15183,63</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>177</customerNumber>
        <checkNumber>CI381435</checkNumber>
        <paymentDate>19.01.2004</paymentDate>
        <amount>47177,59</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>181</customerNumber>
        <checkNumber>CM564612</checkNumber>
        <paymentDate>25.04.2004</paymentDate>
        <amount>22602,36</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>181</customerNumber>
        <checkNumber>GQ132144</checkNumber>
        <paymentDate>30.01.2003</paymentDate>
        <amount>5494,78</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>181</customerNumber>
        <checkNumber>OH367219</checkNumber>
        <paymentDate>16.11.2004</paymentDate>
        <amount>44400,5</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>186</customerNumber>
        <checkNumber>AE192287</checkNumber>
        <paymentDate>10.03.2005</paymentDate>
        <amount>23602,9</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>186</customerNumber>
        <checkNumber>AK412714</checkNumber>
        <paymentDate>27.10.2003</paymentDate>
        <amount>37602,48</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>186</customerNumber>
        <checkNumber>KA602407</checkNumber>
        <paymentDate>21.10.2004</paymentDate>
        <amount>34341,08</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>187</customerNumber>
        <checkNumber>AM968797</checkNumber>
        <paymentDate>03.11.2004</paymentDate>
        <amount>52825,29</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>187</customerNumber>
        <checkNumber>BQ39062</checkNumber>
        <paymentDate>08.12.2004</paymentDate>
        <amount>47159,11</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>187</customerNumber>
        <checkNumber>KL124726</checkNumber>
        <paymentDate>27.03.2003</paymentDate>
        <amount>48425,69</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>189</customerNumber>
        <checkNumber>BO711618</checkNumber>
        <paymentDate>03.10.2004</paymentDate>
        <amount>17359,53</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>189</customerNumber>
        <checkNumber>NM916675</checkNumber>
        <paymentDate>01.03.2004</paymentDate>
        <amount>32538,74</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>198</customerNumber>
        <checkNumber>FI192930</checkNumber>
        <paymentDate>06.12.2004</paymentDate>
        <amount>9658,74</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>198</customerNumber>
        <checkNumber>HQ920205</checkNumber>
        <paymentDate>06.07.2003</paymentDate>
        <amount>6036,96</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>198</customerNumber>
        <checkNumber>IS946883</checkNumber>
        <paymentDate>21.09.2004</paymentDate>
        <amount>5858,56</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>201</customerNumber>
        <checkNumber>DP677013</checkNumber>
        <paymentDate>20.10.2003</paymentDate>
        <amount>23908,24</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>201</customerNumber>
        <checkNumber>OO846801</checkNumber>
        <paymentDate>15.06.2004</paymentDate>
        <amount>37258,94</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>202</customerNumber>
        <checkNumber>HI358554</checkNumber>
        <paymentDate>18.12.2003</paymentDate>
        <amount>36527,61</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>202</customerNumber>
        <checkNumber>IQ627690</checkNumber>
        <paymentDate>08.11.2004</paymentDate>
        <amount>33594,58</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>204</customerNumber>
        <checkNumber>GC697638</checkNumber>
        <paymentDate>13.08.2004</paymentDate>
        <amount>51152,86</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>204</customerNumber>
        <checkNumber>IS150005</checkNumber>
        <paymentDate>24.09.2004</paymentDate>
        <amount>4424,4</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>205</customerNumber>
        <checkNumber>GL756480</checkNumber>
        <paymentDate>04.12.2003</paymentDate>
        <amount>3879,96</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>205</customerNumber>
        <checkNumber>LL562733</checkNumber>
        <paymentDate>05.09.2003</paymentDate>
        <amount>50342,74</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>205</customerNumber>
        <checkNumber>NM739638</checkNumber>
        <paymentDate>06.02.2005</paymentDate>
        <amount>39580,6</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>209</customerNumber>
        <checkNumber>BOAF82044</checkNumber>
        <paymentDate>03.05.2005</paymentDate>
        <amount>35157,75</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>209</customerNumber>
        <checkNumber>ED520529</checkNumber>
        <paymentDate>21.06.2004</paymentDate>
        <amount>4632,31</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>209</customerNumber>
        <checkNumber>PH785937</checkNumber>
        <paymentDate>04.05.2004</paymentDate>
        <amount>36069,26</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>211</customerNumber>
        <checkNumber>BJ535230</checkNumber>
        <paymentDate>09.12.2003</paymentDate>
        <amount>45480,79</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>216</customerNumber>
        <checkNumber>BG407567</checkNumber>
        <paymentDate>09.05.2003</paymentDate>
        <amount>3101,4</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>216</customerNumber>
        <checkNumber>ML780814</checkNumber>
        <paymentDate>06.12.2004</paymentDate>
        <amount>24945,21</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>216</customerNumber>
        <checkNumber>MM342086</checkNumber>
        <paymentDate>14.12.2003</paymentDate>
        <amount>40473,86</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>219</customerNumber>
        <checkNumber>BN17870</checkNumber>
        <paymentDate>02.03.2005</paymentDate>
        <amount>3452,75</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>219</customerNumber>
        <checkNumber>BR941480</checkNumber>
        <paymentDate>18.10.2003</paymentDate>
        <amount>4465,85</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>227</customerNumber>
        <checkNumber>MQ413968</checkNumber>
        <paymentDate>31.10.2003</paymentDate>
        <amount>36164,46</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>227</customerNumber>
        <checkNumber>NU21326</checkNumber>
        <paymentDate>02.11.2004</paymentDate>
        <amount>53745,34</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>233</customerNumber>
        <checkNumber>BOFA23232</checkNumber>
        <paymentDate>20.05.2005</paymentDate>
        <amount>29070,38</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>233</customerNumber>
        <checkNumber>II180006</checkNumber>
        <paymentDate>01.07.2004</paymentDate>
        <amount>22997,45</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>233</customerNumber>
        <checkNumber>JG981190</checkNumber>
        <paymentDate>18.11.2003</paymentDate>
        <amount>16909,84</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>239</customerNumber>
        <checkNumber>NQ865547</checkNumber>
        <paymentDate>15.03.2004</paymentDate>
        <amount>80375,24</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>240</customerNumber>
        <checkNumber>IF245157</checkNumber>
        <paymentDate>16.11.2004</paymentDate>
        <amount>46788,14</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>240</customerNumber>
        <checkNumber>JO719695</checkNumber>
        <paymentDate>28.03.2004</paymentDate>
        <amount>24995,61</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>242</customerNumber>
        <checkNumber>AF40894</checkNumber>
        <paymentDate>22.11.2003</paymentDate>
        <amount>33818,34</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>242</customerNumber>
        <checkNumber>HR224331</checkNumber>
        <paymentDate>03.06.2005</paymentDate>
        <amount>12432,32</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>242</customerNumber>
        <checkNumber>KI744716</checkNumber>
        <paymentDate>21.07.2003</paymentDate>
        <amount>14232,7</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>249</customerNumber>
        <checkNumber>IJ399820</checkNumber>
        <paymentDate>19.09.2004</paymentDate>
        <amount>33924,24</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>249</customerNumber>
        <checkNumber>NE404084</checkNumber>
        <paymentDate>04.09.2004</paymentDate>
        <amount>48298,99</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>250</customerNumber>
        <checkNumber>EQ12267</checkNumber>
        <paymentDate>17.05.2005</paymentDate>
        <amount>17928,09</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>250</customerNumber>
        <checkNumber>HD284647</checkNumber>
        <paymentDate>30.12.2004</paymentDate>
        <amount>26311,63</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>250</customerNumber>
        <checkNumber>HN114306</checkNumber>
        <paymentDate>18.07.2003</paymentDate>
        <amount>23419,47</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>256</customerNumber>
        <checkNumber>EP227123</checkNumber>
        <paymentDate>10.02.2004</paymentDate>
        <amount>5759,42</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>256</customerNumber>
        <checkNumber>HE84936</checkNumber>
        <paymentDate>22.10.2004</paymentDate>
        <amount>53116,99</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>259</customerNumber>
        <checkNumber>EU280955</checkNumber>
        <paymentDate>06.11.2004</paymentDate>
        <amount>61234,67</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>259</customerNumber>
        <checkNumber>GB361972</checkNumber>
        <paymentDate>07.12.2003</paymentDate>
        <amount>27988,47</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>260</customerNumber>
        <checkNumber>IO164641</checkNumber>
        <paymentDate>30.08.2004</paymentDate>
        <amount>37527,58</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>260</customerNumber>
        <checkNumber>NH776924</checkNumber>
        <paymentDate>24.04.2004</paymentDate>
        <amount>29284,42</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>276</customerNumber>
        <checkNumber>EM979878</checkNumber>
        <paymentDate>09.02.2005</paymentDate>
        <amount>27083,78</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>276</customerNumber>
        <checkNumber>KM841847</checkNumber>
        <paymentDate>13.11.2003</paymentDate>
        <amount>38547,19</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>276</customerNumber>
        <checkNumber>LE432182</checkNumber>
        <paymentDate>28.09.2003</paymentDate>
        <amount>41554,73</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>276</customerNumber>
        <checkNumber>OJ819725</checkNumber>
        <paymentDate>30.04.2005</paymentDate>
        <amount>29848,52</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>278</customerNumber>
        <checkNumber>BJ483870</checkNumber>
        <paymentDate>05.12.2004</paymentDate>
        <amount>37654,09</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>278</customerNumber>
        <checkNumber>GP636783</checkNumber>
        <paymentDate>02.03.2003</paymentDate>
        <amount>52151,81</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>278</customerNumber>
        <checkNumber>NI983021</checkNumber>
        <paymentDate>24.11.2003</paymentDate>
        <amount>37723,79</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>282</customerNumber>
        <checkNumber>IA793562</checkNumber>
        <paymentDate>03.08.2003</paymentDate>
        <amount>24013,52</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>282</customerNumber>
        <checkNumber>JT819493</checkNumber>
        <paymentDate>02.08.2004</paymentDate>
        <amount>35806,73</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>282</customerNumber>
        <checkNumber>OD327378</checkNumber>
        <paymentDate>03.01.2005</paymentDate>
        <amount>31835,36</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>286</customerNumber>
        <checkNumber>DR578578</checkNumber>
        <paymentDate>28.10.2004</paymentDate>
        <amount>47411,33</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>286</customerNumber>
        <checkNumber>KH910279</checkNumber>
        <paymentDate>05.09.2004</paymentDate>
        <amount>43134,04</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>298</customerNumber>
        <checkNumber>AJ574927</checkNumber>
        <paymentDate>13.03.2004</paymentDate>
        <amount>47375,92</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>298</customerNumber>
        <checkNumber>LF501133</checkNumber>
        <paymentDate>18.09.2004</paymentDate>
        <amount>61402</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>299</customerNumber>
        <checkNumber>AD304085</checkNumber>
        <paymentDate>24.10.2003</paymentDate>
        <amount>36798,88</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>299</customerNumber>
        <checkNumber>NR157385</checkNumber>
        <paymentDate>05.09.2004</paymentDate>
        <amount>32260,16</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>311</customerNumber>
        <checkNumber>DG336041</checkNumber>
        <paymentDate>15.02.2005</paymentDate>
        <amount>46770,52</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>311</customerNumber>
        <checkNumber>FA728475</checkNumber>
        <paymentDate>06.10.2003</paymentDate>
        <amount>32723,04</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>311</customerNumber>
        <checkNumber>NQ966143</checkNumber>
        <paymentDate>25.04.2004</paymentDate>
        <amount>16212,59</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>314</customerNumber>
        <checkNumber>LQ244073</checkNumber>
        <paymentDate>09.08.2004</paymentDate>
        <amount>45352,47</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>314</customerNumber>
        <checkNumber>MD809704</checkNumber>
        <paymentDate>03.03.2004</paymentDate>
        <amount>16901,38</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>319</customerNumber>
        <checkNumber>HL685576</checkNumber>
        <paymentDate>06.11.2004</paymentDate>
        <amount>42339,76</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>319</customerNumber>
        <checkNumber>OM548174</checkNumber>
        <paymentDate>07.12.2003</paymentDate>
        <amount>36092,4</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>320</customerNumber>
        <checkNumber>GJ597719</checkNumber>
        <paymentDate>18.01.2005</paymentDate>
        <amount>8307,28</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>320</customerNumber>
        <checkNumber>HO576374</checkNumber>
        <paymentDate>20.08.2003</paymentDate>
        <amount>41016,75</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>320</customerNumber>
        <checkNumber>MU817160</checkNumber>
        <paymentDate>24.11.2003</paymentDate>
        <amount>52548,49</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>321</customerNumber>
        <checkNumber>DJ15149</checkNumber>
        <paymentDate>03.11.2003</paymentDate>
        <amount>85559,12</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>321</customerNumber>
        <checkNumber>LA556321</checkNumber>
        <paymentDate>15.03.2005</paymentDate>
        <amount>46781,66</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>323</customerNumber>
        <checkNumber>AL493079</checkNumber>
        <paymentDate>23.05.2005</paymentDate>
        <amount>75020,13</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>323</customerNumber>
        <checkNumber>ES347491</checkNumber>
        <paymentDate>24.06.2004</paymentDate>
        <amount>37281,36</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>323</customerNumber>
        <checkNumber>HG738664</checkNumber>
        <paymentDate>05.07.2003</paymentDate>
        <amount>2880</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>323</customerNumber>
        <checkNumber>PQ803830</checkNumber>
        <paymentDate>24.12.2004</paymentDate>
        <amount>39440,59</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>324</customerNumber>
        <checkNumber>DQ409197</checkNumber>
        <paymentDate>13.12.2004</paymentDate>
        <amount>13671,82</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>324</customerNumber>
        <checkNumber>FP443161</checkNumber>
        <paymentDate>07.07.2003</paymentDate>
        <amount>29429,14</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>324</customerNumber>
        <checkNumber>HB150714</checkNumber>
        <paymentDate>23.11.2003</paymentDate>
        <amount>37455,77</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>328</customerNumber>
        <checkNumber>EN930356</checkNumber>
        <paymentDate>16.04.2004</paymentDate>
        <amount>7178,66</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>328</customerNumber>
        <checkNumber>NR631421</checkNumber>
        <paymentDate>30.05.2004</paymentDate>
        <amount>31102,85</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>333</customerNumber>
        <checkNumber>HL209210</checkNumber>
        <paymentDate>15.11.2003</paymentDate>
        <amount>23936,53</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>333</customerNumber>
        <checkNumber>JK479662</checkNumber>
        <paymentDate>17.10.2003</paymentDate>
        <amount>9821,32</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>333</customerNumber>
        <checkNumber>NF959653</checkNumber>
        <paymentDate>01.03.2005</paymentDate>
        <amount>21432,31</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>334</customerNumber>
        <checkNumber>CS435306</checkNumber>
        <paymentDate>27.01.2005</paymentDate>
        <amount>45785,34</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>334</customerNumber>
        <checkNumber>HH517378</checkNumber>
        <paymentDate>16.08.2003</paymentDate>
        <amount>29716,86</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>334</customerNumber>
        <checkNumber>LF737277</checkNumber>
        <paymentDate>22.05.2004</paymentDate>
        <amount>28394,54</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>339</customerNumber>
        <checkNumber>AP286625</checkNumber>
        <paymentDate>24.10.2004</paymentDate>
        <amount>23333,06</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>339</customerNumber>
        <checkNumber>DA98827</checkNumber>
        <paymentDate>28.11.2003</paymentDate>
        <amount>34606,28</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>344</customerNumber>
        <checkNumber>AF246722</checkNumber>
        <paymentDate>24.11.2003</paymentDate>
        <amount>31428,21</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>344</customerNumber>
        <checkNumber>NJ906924</checkNumber>
        <paymentDate>02.04.2004</paymentDate>
        <amount>15322,93</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>347</customerNumber>
        <checkNumber>DG700707</checkNumber>
        <paymentDate>18.01.2004</paymentDate>
        <amount>21053,69</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>347</customerNumber>
        <checkNumber>LG808674</checkNumber>
        <paymentDate>24.10.2003</paymentDate>
        <amount>20452,5</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>350</customerNumber>
        <checkNumber>BQ602907</checkNumber>
        <paymentDate>11.12.2004</paymentDate>
        <amount>18888,31</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>350</customerNumber>
        <checkNumber>CI471510</checkNumber>
        <paymentDate>25.05.2003</paymentDate>
        <amount>50824,66</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>350</customerNumber>
        <checkNumber>OB648482</checkNumber>
        <paymentDate>29.01.2005</paymentDate>
        <amount>1834,56</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>353</customerNumber>
        <checkNumber>CO351193</checkNumber>
        <paymentDate>10.01.2005</paymentDate>
        <amount>49705,52</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>353</customerNumber>
        <checkNumber>ED878227</checkNumber>
        <paymentDate>21.07.2003</paymentDate>
        <amount>13920,26</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>353</customerNumber>
        <checkNumber>GT878649</checkNumber>
        <paymentDate>21.05.2003</paymentDate>
        <amount>16700,47</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>353</customerNumber>
        <checkNumber>HJ618252</checkNumber>
        <paymentDate>09.06.2005</paymentDate>
        <amount>46656,94</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>357</customerNumber>
        <checkNumber>AG240323</checkNumber>
        <paymentDate>16.12.2003</paymentDate>
        <amount>20220,04</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>357</customerNumber>
        <checkNumber>NB291497</checkNumber>
        <paymentDate>15.05.2004</paymentDate>
        <amount>36442,34</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>362</customerNumber>
        <checkNumber>FP170292</checkNumber>
        <paymentDate>11.07.2004</paymentDate>
        <amount>18473,71</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>362</customerNumber>
        <checkNumber>OG208861</checkNumber>
        <paymentDate>21.09.2004</paymentDate>
        <amount>15059,76</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>363</customerNumber>
        <checkNumber>HL575273</checkNumber>
        <paymentDate>17.11.2004</paymentDate>
        <amount>50799,69</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>363</customerNumber>
        <checkNumber>IS232033</checkNumber>
        <paymentDate>16.01.2003</paymentDate>
        <amount>10223,83</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>363</customerNumber>
        <checkNumber>PN238558</checkNumber>
        <paymentDate>05.12.2003</paymentDate>
        <amount>55425,77</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>379</customerNumber>
        <checkNumber>CA762595</checkNumber>
        <paymentDate>12.02.2005</paymentDate>
        <amount>28322,83</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>379</customerNumber>
        <checkNumber>FR499138</checkNumber>
        <paymentDate>16.09.2003</paymentDate>
        <amount>32680,31</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>379</customerNumber>
        <checkNumber>GB890854</checkNumber>
        <paymentDate>02.08.2004</paymentDate>
        <amount>12530,51</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>381</customerNumber>
        <checkNumber>BC726082</checkNumber>
        <paymentDate>03.12.2004</paymentDate>
        <amount>12081,52</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>381</customerNumber>
        <checkNumber>CC475233</checkNumber>
        <paymentDate>19.04.2003</paymentDate>
        <amount>1627,56</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>381</customerNumber>
        <checkNumber>GB117430</checkNumber>
        <paymentDate>03.02.2005</paymentDate>
        <amount>14379,9</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>381</customerNumber>
        <checkNumber>MS154481</checkNumber>
        <paymentDate>22.08.2003</paymentDate>
        <amount>1128,2</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>382</customerNumber>
        <checkNumber>CC871084</checkNumber>
        <paymentDate>12.05.2003</paymentDate>
        <amount>35826,33</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>382</customerNumber>
        <checkNumber>CT821147</checkNumber>
        <paymentDate>01.08.2004</paymentDate>
        <amount>6419,84</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>382</customerNumber>
        <checkNumber>PH29054</checkNumber>
        <paymentDate>27.11.2004</paymentDate>
        <amount>42813,83</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>385</customerNumber>
        <checkNumber>BN347084</checkNumber>
        <paymentDate>02.12.2003</paymentDate>
        <amount>20644,24</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>385</customerNumber>
        <checkNumber>CP804873</checkNumber>
        <paymentDate>19.11.2004</paymentDate>
        <amount>15822,84</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>385</customerNumber>
        <checkNumber>EK785462</checkNumber>
        <paymentDate>09.03.2003</paymentDate>
        <amount>51001,22</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>386</customerNumber>
        <checkNumber>DO106109</checkNumber>
        <paymentDate>18.11.2003</paymentDate>
        <amount>38524,29</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>386</customerNumber>
        <checkNumber>HG438769</checkNumber>
        <paymentDate>18.07.2004</paymentDate>
        <amount>51619,02</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>398</customerNumber>
        <checkNumber>AJ478695</checkNumber>
        <paymentDate>14.02.2005</paymentDate>
        <amount>33967,73</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>398</customerNumber>
        <checkNumber>DO787644</checkNumber>
        <paymentDate>21.06.2004</paymentDate>
        <amount>22037,91</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>398</customerNumber>
        <checkNumber>JPMR4544</checkNumber>
        <paymentDate>18.05.2005</paymentDate>
        <amount>615,45</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>398</customerNumber>
        <checkNumber>KB54275</checkNumber>
        <paymentDate>29.11.2004</paymentDate>
        <amount>48927,64</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>406</customerNumber>
        <checkNumber>BJMPR4545</checkNumber>
        <paymentDate>23.04.2005</paymentDate>
        <amount>12190,85</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>406</customerNumber>
        <checkNumber>HJ217687</checkNumber>
        <paymentDate>28.01.2004</paymentDate>
        <amount>49165,16</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>406</customerNumber>
        <checkNumber>NA197101</checkNumber>
        <paymentDate>17.06.2004</paymentDate>
        <amount>25080,96</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>412</customerNumber>
        <checkNumber>GH197075</checkNumber>
        <paymentDate>25.07.2004</paymentDate>
        <amount>35034,57</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>412</customerNumber>
        <checkNumber>PJ434867</checkNumber>
        <paymentDate>14.04.2004</paymentDate>
        <amount>31670,37</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>415</customerNumber>
        <checkNumber>ER54537</checkNumber>
        <paymentDate>28.09.2004</paymentDate>
        <amount>31310,09</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>424</customerNumber>
        <checkNumber>KF480160</checkNumber>
        <paymentDate>07.12.2004</paymentDate>
        <amount>25505,98</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>424</customerNumber>
        <checkNumber>LM271923</checkNumber>
        <paymentDate>16.04.2003</paymentDate>
        <amount>21665,98</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>424</customerNumber>
        <checkNumber>OA595449</checkNumber>
        <paymentDate>31.10.2003</paymentDate>
        <amount>22042,37</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>447</customerNumber>
        <checkNumber>AO757239</checkNumber>
        <paymentDate>15.09.2003</paymentDate>
        <amount>6631,36</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>447</customerNumber>
        <checkNumber>ER615123</checkNumber>
        <paymentDate>25.06.2003</paymentDate>
        <amount>17032,29</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>447</customerNumber>
        <checkNumber>OU516561</checkNumber>
        <paymentDate>17.12.2004</paymentDate>
        <amount>26304,13</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>448</customerNumber>
        <checkNumber>FS299615</checkNumber>
        <paymentDate>18.04.2005</paymentDate>
        <amount>27966,54</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>448</customerNumber>
        <checkNumber>KR822727</checkNumber>
        <paymentDate>30.09.2004</paymentDate>
        <amount>48809,9</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>450</customerNumber>
        <checkNumber>EF485824</checkNumber>
        <paymentDate>21.06.2004</paymentDate>
        <amount>59551,38</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>452</customerNumber>
        <checkNumber>ED473873</checkNumber>
        <paymentDate>15.11.2003</paymentDate>
        <amount>27121,9</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>452</customerNumber>
        <checkNumber>FN640986</checkNumber>
        <paymentDate>20.11.2003</paymentDate>
        <amount>15130,97</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>452</customerNumber>
        <checkNumber>HG635467</checkNumber>
        <paymentDate>03.05.2005</paymentDate>
        <amount>8807,12</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>455</customerNumber>
        <checkNumber>HA777606</checkNumber>
        <paymentDate>05.12.2003</paymentDate>
        <amount>38139,18</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>455</customerNumber>
        <checkNumber>IR662429</checkNumber>
        <paymentDate>12.05.2004</paymentDate>
        <amount>32239,47</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>456</customerNumber>
        <checkNumber>GJ715659</checkNumber>
        <paymentDate>13.11.2004</paymentDate>
        <amount>27550,51</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>456</customerNumber>
        <checkNumber>MO743231</checkNumber>
        <paymentDate>30.04.2004</paymentDate>
        <amount>1679,92</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>458</customerNumber>
        <checkNumber>DD995006</checkNumber>
        <paymentDate>15.11.2004</paymentDate>
        <amount>33145,56</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>458</customerNumber>
        <checkNumber>NA377824</checkNumber>
        <paymentDate>06.02.2004</paymentDate>
        <amount>22162,61</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>458</customerNumber>
        <checkNumber>OO606861</checkNumber>
        <paymentDate>13.06.2003</paymentDate>
        <amount>57131,92</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>462</customerNumber>
        <checkNumber>ED203908</checkNumber>
        <paymentDate>15.04.2005</paymentDate>
        <amount>30293,77</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>462</customerNumber>
        <checkNumber>GC60330</checkNumber>
        <paymentDate>08.11.2003</paymentDate>
        <amount>9977,85</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>462</customerNumber>
        <checkNumber>PE176846</checkNumber>
        <paymentDate>27.11.2004</paymentDate>
        <amount>48355,87</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>471</customerNumber>
        <checkNumber>AB661578</checkNumber>
        <paymentDate>28.07.2004</paymentDate>
        <amount>9415,13</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>471</customerNumber>
        <checkNumber>CO645196</checkNumber>
        <paymentDate>10.12.2003</paymentDate>
        <amount>35505,63</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>473</customerNumber>
        <checkNumber>LL427009</checkNumber>
        <paymentDate>17.02.2004</paymentDate>
        <amount>7612,06</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>473</customerNumber>
        <checkNumber>PC688499</checkNumber>
        <paymentDate>27.10.2003</paymentDate>
        <amount>17746,26</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>475</customerNumber>
        <checkNumber>JP113227</checkNumber>
        <paymentDate>09.12.2003</paymentDate>
        <amount>7678,25</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>475</customerNumber>
        <checkNumber>PB951268</checkNumber>
        <paymentDate>13.02.2004</paymentDate>
        <amount>36070,47</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>484</customerNumber>
        <checkNumber>GK294076</checkNumber>
        <paymentDate>26.10.2004</paymentDate>
        <amount>3474,66</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>484</customerNumber>
        <checkNumber>JH546765</checkNumber>
        <paymentDate>29.11.2003</paymentDate>
        <amount>47513,19</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>486</customerNumber>
        <checkNumber>BL66528</checkNumber>
        <paymentDate>14.04.2004</paymentDate>
        <amount>5899,38</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>486</customerNumber>
        <checkNumber>HS86661</checkNumber>
        <paymentDate>23.11.2004</paymentDate>
        <amount>45994,07</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>486</customerNumber>
        <checkNumber>JB117768</checkNumber>
        <paymentDate>20.03.2003</paymentDate>
        <amount>25833,14</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>487</customerNumber>
        <checkNumber>AH612904</checkNumber>
        <paymentDate>28.09.2003</paymentDate>
        <amount>29997,09</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>487</customerNumber>
        <checkNumber>PT550181</checkNumber>
        <paymentDate>29.02.2004</paymentDate>
        <amount>12573,28</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>489</customerNumber>
        <checkNumber>OC773849</checkNumber>
        <paymentDate>04.12.2003</paymentDate>
        <amount>22275,73</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>489</customerNumber>
        <checkNumber>PO860906</checkNumber>
        <paymentDate>31.01.2004</paymentDate>
        <amount>7310,42</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>495</customerNumber>
        <checkNumber>BH167026</checkNumber>
        <paymentDate>26.12.2003</paymentDate>
        <amount>59265,14</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>495</customerNumber>
        <checkNumber>FN155234</checkNumber>
        <paymentDate>14.05.2004</paymentDate>
        <amount>6276,6</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>496</customerNumber>
        <checkNumber>EU531600</checkNumber>
        <paymentDate>25.05.2005</paymentDate>
        <amount>30253,75</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>496</customerNumber>
        <checkNumber>MB342426</checkNumber>
        <paymentDate>16.07.2003</paymentDate>
        <amount>32077,44</amount>
	</payment>');
	INSERT INTO payments VALUES ('<?xml version="1.0" encoding="UTF-8"?>

<payment>
		<customerNumber>496</customerNumber>
        <checkNumber>MN89921</checkNumber>
        <paymentDate>31.12.2004</paymentDate>
        <amount>52166</amount>
	</payment>');
