--Crud_3
-- FLUSH 
ALTER SYSTEM FLUSH buffer_cache;
ALTER SYSTEM FLUSH shared_pool;

VARIABLE  START_TIME_CRUD_3 NUMBER;
EXEC :START_TIME_CRUD_3 := EXTRACT(SECOND FROM SYSTIMESTAMP);
-- START MIERZENIA CZASU

INSERT INTO employees(employeeNumber,lastName,firstName,extension,email,officeCode,reportsTo,jobTitle) 
VALUES (17002,'Gerard','Martin','x2312','mgerard@classicmodelcars.com','4',2501,'Sales Rep');

UPDATE EMPLOYEES EMP
SET EMP.JOBTITLE = 'Sales Manager'
WHERE EMPLOYEENUMBER = (
	SELECT CANBEMANAGERNUMBERS FROM (
		SELECT EMP.REPORTSTO AS CANBEMANAGERNUMBERS
		FROM EMPLOYEES EMP
		GROUP BY EMP.REPORTSTO, EMP.JOBTITLE
		HAVING COUNT(EMP.EMPLOYEENUMBER) > 5 
		AND JOBTITLE NOT LIKE 'Sales Manager'
	) WHERE CANBEMANAGERNUMBERS = 2501
);

VARIABLE  TIME_FOR_CRUD_3 NUMBER;
EXEC :TIME_FOR_CRUD_3 := EXTRACT(SECOND FROM SYSTIMESTAMP)-:START_TIME_CRUD_3;
spool etap2_results.txt append;
PRINT TIME_FOR_CRUD_3;
spool off;
ROLLBACK;