-- CRUDy odpowiadajace regulom z rules.sql

-- 3
UPDATE EMPLOYEES EMP
SET EMP.JOBTITLE = 'Sales Manager'
WHERE EMPLOYEENUMBER = (
	SELECT CANBEMANAGERNUMBERS FROM (
		SELECT EMP.REPORTSTO AS CANBEMANAGERNUMBERS
		FROM EMPLOYEES EMP
		GROUP BY EMP.REPORTSTO, EMP.JOBTITLE
		HAVING COUNT(EMP.EMPLOYEENUMBER) > 5 
		AND JOBTITLE NOT LIKE 'Sales Manager'
	) WHERE CANBEMANAGERNUMBERS = 2501
);