--Crud_4
-- FLUSH 
ALTER SYSTEM FLUSH buffer_cache;
ALTER SYSTEM FLUSH shared_pool;

VARIABLE  START_TIME_CRUD_TOTAL NUMBER;
EXEC :START_TIME_CRUD_TOTAL := EXTRACT(SECOND FROM SYSTIMESTAMP);
-- START MIERZENIA CZASU

--1
UPDATE ORDERS ORD
SET ORD.STATUS = 'On Road',
ORD.REQUIREDDATE = ORD.REQUIREDDATE +1
WHERE ORD.ORDERNUMBER = 10420;

UPDATE ORDERS ORD
SET ORD.STATUS = 'On Road',
ORD.REQUIREDDATE = ORD.REQUIREDDATE +1
WHERE ORD.ORDERNUMBER = 10421;

UPDATE ORDERS ORD
SET ORD.STATUS = 'On Road',
ORD.REQUIREDDATE = ORD.REQUIREDDATE +1
WHERE ORD.ORDERNUMBER = 10422;

UPDATE ORDERS ORD
SET ORD.STATUS = 'On Road',
ORD.REQUIREDDATE = ORD.REQUIREDDATE +1
WHERE ORD.ORDERNUMBER = 10423;


UPDATE ORDERS ORD
SET ORD.STATUS = 'On Road',
ORD.REQUIREDDATE = ORD.REQUIREDDATE +1
WHERE ORD.ORDERNUMBER = 10424;
---2
insert  into payments(customerNumber,checkNumber,paymentDate,amount) 
values (103,'NEW236335',to_date('2020-02-19','YYYY-MM-DD'),6066.78);

 UPDATE CUSTOMERS CUST
 SET CUST.CREDITLIMIT = CUST.CREDITLIMIT+100
 WHERE CUST.CUSTOMERNUMBER = 103;

insert  into payments(customerNumber,checkNumber,paymentDate,amount) 
values (103,'NEW236336',to_date('2020-02-19','YYYY-MM-DD'),6066.78);

 UPDATE CUSTOMERS CUST
 SET CUST.CREDITLIMIT = CUST.CREDITLIMIT+100
 WHERE CUST.CUSTOMERNUMBER = 103;

insert  into payments(customerNumber,checkNumber,paymentDate,amount) 
values (103,'NEW236337',to_date('2020-02-19','YYYY-MM-DD'),6066.78);

 UPDATE CUSTOMERS CUST
 SET CUST.CREDITLIMIT = CUST.CREDITLIMIT+100
 WHERE CUST.CUSTOMERNUMBER = 103;
 
 insert  into payments(customerNumber,checkNumber,paymentDate,amount) 
values (103,'NEW236338',to_date('2020-02-19','YYYY-MM-DD'),6066.78);

 UPDATE CUSTOMERS CUST
 SET CUST.CREDITLIMIT = CUST.CREDITLIMIT+100
 WHERE CUST.CUSTOMERNUMBER = 103;
 
 insert  into payments(customerNumber,checkNumber,paymentDate,amount) 
values (103,'NEW236339',to_date('2020-02-19','YYYY-MM-DD'),6066.78);

 UPDATE CUSTOMERS CUST
 SET CUST.CREDITLIMIT = CUST.CREDITLIMIT+100
 WHERE CUST.CUSTOMERNUMBER = 103;
 
 --3
 UPDATE EMPLOYEES EMP
SET EMP.JOBTITLE = 'Sales Manager'
WHERE EMPLOYEENUMBER = (
	SELECT CANBEMANAGERNUMBERS FROM (
		SELECT EMP.REPORTSTO AS CANBEMANAGERNUMBERS
		FROM EMPLOYEES EMP
		GROUP BY EMP.REPORTSTO, EMP.JOBTITLE
		HAVING COUNT(EMP.EMPLOYEENUMBER) > 5 
		AND JOBTITLE NOT LIKE 'Sales Manager'
	) WHERE CANBEMANAGERNUMBERS = 2501
); 


-----4

INSERT INTO orderdetails(orderNumber,productCode,quantityOrdered,priceEach,orderLineNumber) 
VALUES (10328,'S50_1392',5,10,2);

INSERT INTO orderdetails(orderNumber,productCode,quantityOrdered,priceEach,orderLineNumber) 
VALUES (10328,'S18_3278',10,15,2);

INSERT INTO orderdetails(orderNumber,productCode,quantityOrdered,priceEach,orderLineNumber) 
VALUES (10328,'S18_3482',15,15,2);

INSERT INTO orderdetails(orderNumber,productCode,quantityOrdered,priceEach,orderLineNumber) 
VALUES (10328,'S18_3685',20,25,2);

INSERT INTO orderdetails(orderNumber,productCode,quantityOrdered,priceEach,orderLineNumber) 
VALUES (10328,'S18_3782',25,30,2);

UPDATE PRODUCTS PRD
SET PRD.QUANTITYINSTOCK = PRD.QUANTITYINSTOCK - 5
WHERE PRD.PRODUCTCODE = 'S50_1392';

UPDATE PRODUCTS PRD
SET PRD.QUANTITYINSTOCK = PRD.QUANTITYINSTOCK - 10
WHERE PRD.PRODUCTCODE = 'S18_3278';

UPDATE PRODUCTS PRD
SET PRD.QUANTITYINSTOCK = PRD.QUANTITYINSTOCK - 15
WHERE PRD.PRODUCTCODE = 'S18_3482';

UPDATE PRODUCTS PRD
SET PRD.QUANTITYINSTOCK = PRD.QUANTITYINSTOCK - 20
WHERE PRD.PRODUCTCODE = 'S18_3685';

UPDATE PRODUCTS PRD
SET PRD.QUANTITYINSTOCK = PRD.QUANTITYINSTOCK - 25
WHERE PRD.PRODUCTCODE = 'S18_3782';

VARIABLE  TIME_FOR_CRUD_TOTAL NUMBER;
EXEC :TIME_FOR_CRUD_TOTAL := EXTRACT(SECOND FROM SYSTIMESTAMP)-:START_TIME_CRUD_TOTAL;
spool etap2_results.txt append;
PRINT TIME_FOR_CRUD_TOTAL;
spool off;
ROLLBACK;