-- CRUDy odpowiadajace regulom z rules.sql

-- 3
INSERT INTO employees(employeeNumber,lastName,firstName,extension,email,officeCode,reportsTo,jobTitle) 
VALUES (17002,'Gerard','Martin','x2312','mgerard@classicmodelcars.com','4',2501,'Sales Rep');

UPDATE EMPLOYEES EMP
SET EMP.JOBTITLE = 'Sales Manager'
WHERE EMPLOYEENUMBER = (
	SELECT CANBEMANAGERNUMBERS FROM (
		SELECT EMP.REPORTSTO AS CANBEMANAGERNUMBERS
		FROM EMPLOYEES EMP
		GROUP BY EMP.REPORTSTO, EMP.JOBTITLE
		HAVING COUNT(EMP.EMPLOYEENUMBER) > 5 
		AND JOBTITLE NOT LIKE 'Sales Manager'
	) WHERE CANBEMANAGERNUMBERS = 2501
);

-- 4
INSERT INTO orderdetails(orderNumber,productCode,quantityOrdered,priceEach,orderLineNumber) 
VALUES (10328,'S50_1392',5,10,2);

INSERT INTO orderdetails(orderNumber,productCode,quantityOrdered,priceEach,orderLineNumber) 
VALUES (10328,'S18_3278',10,15,2);

INSERT INTO orderdetails(orderNumber,productCode,quantityOrdered,priceEach,orderLineNumber) 
VALUES (10328,'S18_3482',15,15,2);

INSERT INTO orderdetails(orderNumber,productCode,quantityOrdered,priceEach,orderLineNumber) 
VALUES (10328,'S18_3685',20,25,2);

INSERT INTO orderdetails(orderNumber,productCode,quantityOrdered,priceEach,orderLineNumber) 
VALUES (10328,'S18_3782',25,30,2);

UPDATE PRODUCTS PRD
SET PRD.QUANTITYINSTOCK = PRD.QUANTITYINSTOCK - 5
WHERE PRD.PRODUCTCODE = 'S50_1392';

UPDATE PRODUCTS PRD
SET PRD.QUANTITYINSTOCK = PRD.QUANTITYINSTOCK - 10
WHERE PRD.PRODUCTCODE = 'S18_3278';

UPDATE PRODUCTS PRD
SET PRD.QUANTITYINSTOCK = PRD.QUANTITYINSTOCK - 15
WHERE PRD.PRODUCTCODE = 'S18_3482';

UPDATE PRODUCTS PRD
SET PRD.QUANTITYINSTOCK = PRD.QUANTITYINSTOCK - 20
WHERE PRD.PRODUCTCODE = 'S18_3685';

UPDATE PRODUCTS PRD
SET PRD.QUANTITYINSTOCK = PRD.QUANTITYINSTOCK - 25
WHERE PRD.PRODUCTCODE = 'S18_3782';